# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

init_bdd <- function(library = "buddy", node_num = 0L, cache_size = 0L, bdd_name = "default") {
    invisible(.Call('_rbdd_init_bdd', PACKAGE = 'rbdd', library, node_num, cache_size, bdd_name))
}

new_variable <- function(variable_name, var_type = "boolean", bdd_name = "default") {
    .Call('_rbdd_new_variable', PACKAGE = 'rbdd', variable_name, var_type, bdd_name)
}

new_variable_from_expression <- function(expression, bdd_name = "default") {
    .Call('_rbdd_new_variable_from_expression', PACKAGE = 'rbdd', expression, bdd_name)
}

print_variables <- function(bdd_name = "default") {
    invisible(.Call('_rbdd_print_variables', PACKAGE = 'rbdd', bdd_name))
}

expression_to_string <- function(expression, bdd_name = "default") {
    invisible(.Call('_rbdd_expression_to_string', PACKAGE = 'rbdd', expression, bdd_name))
}

apply_bdd <- function(expression, bdd_name = "default") {
    invisible(.Call('_rbdd_apply_bdd', PACKAGE = 'rbdd', expression, bdd_name))
}

get_node_num <- function(bdd_name = "default") {
    .Call('_rbdd_get_node_num', PACKAGE = 'rbdd', bdd_name)
}

save_bdd <- function(file_name, bdd_name = "default") {
    invisible(.Call('_rbdd_save_bdd', PACKAGE = 'rbdd', file_name, bdd_name))
}

read_bdd <- function(file_name, bdd_name = "default") {
    invisible(.Call('_rbdd_read_bdd', PACKAGE = 'rbdd', file_name, bdd_name))
}

done_bdd <- function(bdd_name = "default") {
    invisible(.Call('_rbdd_done_bdd', PACKAGE = 'rbdd', bdd_name))
}

is_initialized <- function(bdd_name = "default") {
    .Call('_rbdd_is_initialized', PACKAGE = 'rbdd', bdd_name)
}

reset_bdd <- function(bdd_name = "default") {
    invisible(.Call('_rbdd_reset_bdd', PACKAGE = 'rbdd', bdd_name))
}

set_cache_ratio <- function(cache_ratio, bdd_name = "default") {
    invisible(.Call('_rbdd_set_cache_ratio', PACKAGE = 'rbdd', cache_ratio, bdd_name))
}

set_max_node_num <- function(size, bdd_name = "default") {
    invisible(.Call('_rbdd_set_max_node_num', PACKAGE = 'rbdd', size, bdd_name))
}

reorder_bdd <- function(reorder_method = "sift", bdd_name = "default") {
    invisible(.Call('_rbdd_reorder_bdd', PACKAGE = 'rbdd', reorder_method, bdd_name))
}

add_cnf_var <- function(name, bdd_name = "default") {
    .Call('_rbdd_add_cnf_var', PACKAGE = 'rbdd', name, bdd_name)
}

get_bdd_library <- function(bdd_name = "default") {
    invisible(.Call('_rbdd_get_bdd_library', PACKAGE = 'rbdd', bdd_name))
}

same_bdd <- function(name_bdd_1, name_bdd_2) {
    .Call('_rbdd_same_bdd', PACKAGE = 'rbdd', name_bdd_1, name_bdd_2)
}

print_bdd <- function(bdd_name = "default") {
    invisible(.Call('_rbdd_print_bdd', PACKAGE = 'rbdd', bdd_name))
}

restrict_bdd <- function(expression, var_to_restrict, variable_name, positive_form = TRUE, bdd_name = "default") {
    .Call('_rbdd_restrict_bdd', PACKAGE = 'rbdd', expression, var_to_restrict, variable_name, positive_form, bdd_name)
}

traverse_scalar <- function(function_to_apply, initial_scalar = 0L, bdd_name = "default") {
    .Call('_rbdd_traverse_scalar', PACKAGE = 'rbdd', function_to_apply, initial_scalar, bdd_name)
}

traverse_vector <- function(function_to_apply, initial_vector = as.numeric( c(1, 1)), bdd_name = "default") {
    .Call('_rbdd_traverse_vector', PACKAGE = 'rbdd', function_to_apply, initial_vector, bdd_name)
}

