# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bdd_manager_init <- function(library = "cudd", node_num = 0L, cache_size = 0L, bdd_name = "default") {
    invisible(.Call('_rbdd_bdd_manager_init', PACKAGE = 'rbdd', library, node_num, cache_size, bdd_name))
}

bdd_manager_quit <- function(bdd_name = "default") {
    invisible(.Call('_rbdd_bdd_manager_quit', PACKAGE = 'rbdd', bdd_name))
}

bdd_manager_reset <- function(bdd_name = "default") {
    invisible(.Call('_rbdd_bdd_manager_reset', PACKAGE = 'rbdd', bdd_name))
}

bdd_new_variable <- function(variable_name, var_type = "boolean", bdd_name = "default") {
    .Call('_rbdd_bdd_new_variable', PACKAGE = 'rbdd', variable_name, var_type, bdd_name)
}

bdd_parse_cnf <- function(file, bdd_name = "default", score = "none", window = 1L, reorder = "minspan", min_nodes = 100000L, line_length = 27L, dyn_comp = TRUE) {
    .Call('_rbdd_bdd_parse_cnf', PACKAGE = 'rbdd', file, bdd_name, score, window, reorder, min_nodes, line_length, dyn_comp)
}

bdd_parse_splot <- function(file, bdd_name = "default", score = "none", window = 1L, reorder = "minspan", min_nodes = 100000L, line_length = 27L, dyn_comp = TRUE) {
    .Call('_rbdd_bdd_parse_splot', PACKAGE = 'rbdd', file, bdd_name, score, window, reorder, min_nodes, line_length, dyn_comp)
}

bdd_parse_boolstr <- function(expression, bdd_name = "default") {
    .Call('_rbdd_bdd_parse_boolstr', PACKAGE = 'rbdd', expression, bdd_name)
}

bdd_order <- function(reorder_method = "sift", bdd_name = "default") {
    invisible(.Call('_rbdd_bdd_order', PACKAGE = 'rbdd', reorder_method, bdd_name))
}

bdd_write <- function(file_name, bdd_name = "default") {
    invisible(.Call('_rbdd_bdd_write', PACKAGE = 'rbdd', file_name, bdd_name))
}

bdd_read <- function(file_name, bdd_name = "default") {
    invisible(.Call('_rbdd_bdd_read', PACKAGE = 'rbdd', file_name, bdd_name))
}

bdd_identical <- function(name_bdd_1, name_bdd_2) {
    .Call('_rbdd_bdd_identical', PACKAGE = 'rbdd', name_bdd_1, name_bdd_2)
}

bdd_restrict <- function(restriction, restriction_name, expression = 0L, positive_form = TRUE, bdd_name = "default") {
    .Call('_rbdd_bdd_restrict', PACKAGE = 'rbdd', restriction, restriction_name, expression, positive_form, bdd_name)
}

bdd_traverse <- function(value_zero, value_one, function_to_apply, return_node = FALSE, num_threads = 1L, bdd_name = "default", trace = FALSE) {
    .Call('_rbdd_bdd_traverse', PACKAGE = 'rbdd', value_zero, value_one, function_to_apply, return_node, num_threads, bdd_name, trace)
}

bdd_traverse_root_node <- function(bdd_name = "default") {
    .Call('_rbdd_bdd_traverse_root_node', PACKAGE = 'rbdd', bdd_name)
}

bdd_traverse_is_node_zero <- function(node, bdd_name = "default") {
    .Call('_rbdd_bdd_traverse_is_node_zero', PACKAGE = 'rbdd', node, bdd_name)
}

bdd_traverse_is_node_one <- function(node, bdd_name = "default") {
    .Call('_rbdd_bdd_traverse_is_node_one', PACKAGE = 'rbdd', node, bdd_name)
}

bdd_traverse_get_level <- function(node, bdd_name = "default") {
    .Call('_rbdd_bdd_traverse_get_level', PACKAGE = 'rbdd', node, bdd_name)
}

bdd_traverse_get_var_at_pos <- function(pos, bdd_name = "default") {
    .Call('_rbdd_bdd_traverse_get_var_at_pos', PACKAGE = 'rbdd', pos, bdd_name)
}

bdd_traverse_get_children <- function(node, bdd_name = "default") {
    .Call('_rbdd_bdd_traverse_get_children', PACKAGE = 'rbdd', node, bdd_name)
}

bdd_info_variables <- function(xverbose = TRUE, bdd_name = "default") {
    .Call('_rbdd_bdd_info_variables', PACKAGE = 'rbdd', xverbose, bdd_name)
}

bdd_info_variable_number <- function(bdd_name = "default") {
    .Call('_rbdd_bdd_info_variable_number', PACKAGE = 'rbdd', bdd_name)
}

bdd_info_boolstr <- function(expression, bdd_name = "default") {
    invisible(.Call('_rbdd_bdd_info_boolstr', PACKAGE = 'rbdd', expression, bdd_name))
}

bdd_info_node_number <- function(bdd_name = "default") {
    .Call('_rbdd_bdd_info_node_number', PACKAGE = 'rbdd', bdd_name)
}

bdd_manager_is_initialized <- function(bdd_name = "default") {
    .Call('_rbdd_bdd_manager_is_initialized', PACKAGE = 'rbdd', bdd_name)
}

bdd_info_manager_library <- function(bdd_name = "default") {
    invisible(.Call('_rbdd_bdd_info_manager_library', PACKAGE = 'rbdd', bdd_name))
}

bdd_print <- function(bdd_name = "default") {
    invisible(.Call('_rbdd_bdd_print', PACKAGE = 'rbdd', bdd_name))
}

bdd_set_cache_ratio <- function(cache_ratio, bdd_name = "default") {
    invisible(.Call('_rbdd_bdd_set_cache_ratio', PACKAGE = 'rbdd', cache_ratio, bdd_name))
}

bdd_set_max_node_num <- function(size, bdd_name = "default") {
    invisible(.Call('_rbdd_bdd_set_max_node_num', PACKAGE = 'rbdd', size, bdd_name))
}

bdd_get_var_probabilities <- function(num_threads = 1L, trace = FALSE, fast = FALSE, bdd_name = "default", restriction = "") {
    thelist <- .Call('_rbdd_bdd_get_var_probabilities', PACKAGE = 'rbdd', num_threads, trace, fast, bdd_name, restriction)
    thelength <- length(thelist)/2
    result <- as.list(0, rep(0, thelength))
    i <- 1
    while (i <= thelength) {
        inter <- c()
        inter[1] <- thelist[2*i - 1]
        inter[2] <- Rmpfr::mpfr(thelist[2*i], 128)
        result[[i]] <- inter
        i <- i + 1
    }
    return(result)
}

bdd_get_sat_distribution <- function(num_threads = 1L, trace = FALSE, fast = FALSE, bdd_name = "default", restriction = "") {
    thelist <- .Call('_rbdd_bdd_get_sat_distribution', PACKAGE = 'rbdd', num_threads, trace, fast, bdd_name, restriction)
    result <- c(rep(gmp::as.bigz(0), length(thelist)))
    i <- 1
    while (i <= length(thelist)) {
        result[[i]] <- gmp::as.bigz(thelist[i])
        i <- i + 1
    }
    return(result)
}

bdd_get_core_dead <- function(num_threads = 1L, trace = FALSE, fast = FALSE, bdd_name = "default") {
    .Call('_rbdd_bdd_get_core_dead', PACKAGE = 'rbdd', num_threads, trace, fast, bdd_name)
}

bdd_get_uniform_random_sampling <- function(name = FALSE, num_threads = 1L, trace = FALSE, fast = FALSE, bdd_name = "default") {
    .Call('_rbdd_bdd_get_uniform_random_sampling', PACKAGE = 'rbdd', name, num_threads, trace, fast, bdd_name)
}

